"""adding branch field into project

Revision ID: 15aec38f0175
Revises: b2fdeeb2bc73
Create Date: 2024-11-29 14:26:59.060680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15aec38f0175'
down_revision: Union[str, None] = 'b2fdeeb2bc73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('branch', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'branch')
    # ### end Alembic commands ###
