"""adding codemod field into db

Revision ID: 26b3fa98e0f9
Revises: c38a3b6d5bd1
Create Date: 2024-12-04 01:30:12.942016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b3fa98e0f9'
down_revision: Union[str, None] = 'c38a3b6d5bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
