"""adding codemod field into db

Revision ID: c38a3b6d5bd1
Revises: 4b78abefc395
Create Date: 2024-12-04 00:22:43.285711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c38a3b6d5bd1'
down_revision: Union[str, None] = '4b78abefc395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('codemod_status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'codemod_status')
    # ### end Alembic commands ###
